

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
# family = "CaskaydiaCove Nerd Font"
family = "DejaVu Sans Mono"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
family = "DejaVu Sans Mono"
style = "Bold Italic"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
family = "DejaVu Sans Mono"
style = "Italic"

[font.normal]
# family = "CaskaydiaCove Nerd Font"
family = "DejaVu Sans Mono"
style = "Regular"

