[env]
TERM = "xterm-256color"

[window]
opacity = 1
decorations = "full"  # Can be "none" for borderless
padding.x= 10 
padding.y = 10
dynamic_padding = true
startup_mode= "Windowed"

[font]
normal = { family = "Agave Nerd Font", style = "Regular" }
bold = { family = "Agave Nerd Font", style = "Bold" }
italic = { family = "Agave Nerd Font", style = "Italic" }
bold_italic = { family = "Agave Nerd Font", style = "Bold Italic" }
size = 16.0

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[colors.primary]
background = "#2C2C2C"  # Dark background
foreground = "#E6D6AC"  # Light text

[colors.cursor]
text = "#E6D6AC"
cursor = "#F5E0DC"

[colors.normal]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[colors.bright]
black = "#585B70"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = "#45475A"
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#BAC2DE"

[bell]
animation = "EaseOut"
duration = 100
color = "#F38BA8"

[terminal]
shell = { program = "/bin/bash", args = ["-c", "tmux new-session -A -s main"] }

